### ISSUE TITLE
Usage of Wire library.

### ISSUE THREAD

**Issue by Koepel** [ErcBunny/VTOL_osprey#1]
You have included the file MPU6050.cpp, but that has a number of issues: https://github.com/jarzebski/Arduino-MPU6050/issues/4
Explanation: [Common-mistakes](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes), number 1, 2, 3 and 5.

**Comment by ErcBunny** [comment]
Fixed in the latest commit.

**Comment by Koepel** [comment]
Now that the bugs are removed, did you notice that the functions `fastRegister8()` and `readRegister8()` are the same ?

**Comment by ErcBunny** [comment]
Umm...Yeah...But I did not pay attention to that until you mention it...I've never looked into this library before...So, any suggestions?

**Comment by Koepel** [comment]
You can keep it as it is, or use only the readRegister8() and change the calls to fastRegister8() to readRegister8().

**Comment by ErcBunny** [comment]
Oh, by the way, I am just starting to get the hang of Github and not so familiar with everything around yet. I don't quite understand what do you mean by _If he can fix it, why can't you_ in jarzebski's repo? What are all of these? Any hint? Thanks a lot.

**Comment by Koepel** [comment]
That's just me, trying to annoy jarzebski, until he is finally fed up with me and fixes it. But that is not working so far.

I was telling jarzebski, that if you can fix, then he should be able to fix it as well.
The wrong use of the Wire library is copied a lot, and I see the the wrong use of the Wire library too often on Github and in forums.

**Comment by ErcBunny** [comment]
Mpu6050 seems to be unnecessary with mavlink support and the modified library is kept in the backup branch just in case that somebody needs it.
